name: Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (prod only)
      run: |
        npm install
        npm prune --production

    - name: Bundle with esbuild
      run: |
        npx esbuild src/index.ts \
          --bundle --platform=node --target=node18 \
          --outfile=function.js \
          --minify

    - name: Zip Lambda function
      run: |
        zip function.zip function.js package.json package-lock.json

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to Lambda via CLI
      run: |
        aws lambda update-function-code --function-name NotAloneGameHandler --zip-file fileb://function.zip
