name: Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (prod only)
      run: |
        npm install
        npm prune --production

    - name: Bundle with esbuild
      run: |
        npx esbuild src/mult_backend/gameHandler.js --bundle --platform=node --target=node18 --outfile=gamehandler.js --minify
        npx esbuild src/mult_backend/connect.js --bundle --platform=node --target=node18 --outfile=connect.js --minify
        npx esbuild src/mult_backend/disconnect.js --bundle --platform=node --target=node18 --outfile=disconnect.js --minify

    - name: Zip gamehandler
      run: zip -j gamehandler.zip gamehandler.js

    - name: Zip connect
      run: zip -j connect.zip connect.js

    - name: Zip disconnect
      run: zip -j disconnect.zip disconnect.js

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy gamehandler Lambda
      run: aws lambda update-function-code --function-name NotAloneGameHandler --zip-file fileb://gamehandler.zip

    - name: Deploy connect Lambda
      run: aws lambda update-function-code --function-name NotAloneConnect --zip-file fileb://connect.zip

    - name: Deploy disconnect Lambda
      run: aws lambda update-function-code --function-name NotAloneDisconnect --zip-file fileb://disconnect.zip
